name: Deploymulti

on:
  push:

jobs:
  # Build and publish the commit to docker
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'growthbook/growthbook' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install Depot CLI
        uses: depot/setup-action@v1

      - name: Prepare build metadata
        id: metadata
        run: |
          # Store current git hash and date in files
          mkdir -p buildinfo
          echo "${GITHUB_SHA}" > buildinfo/SHA
          printf '%(%Y-%m-%dT%H:%M:%SZ)T' > buildinfo/DATE
          echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build, tag, and push a multiplatform image to Docker Hub
        uses: depot/build-push-action@v1
        with:
          push: true
          context: .
          project: vmp2ssvj9r
          tags: |
            growthbook/growthbook:multiplatform
            growthbook/growqthbook:git-${{ steps.metadata.outputs.sha }}
          platforms: linux/amd64,linux/arm64
